library(tsModel)
library(splines)
source("R/datastructures.R")
## d0 <- readAPTSData("inst/chic.rds")
d0 <- readAPTSData("inst/ny.rds")
ch <- checkData(d0)
base <- glm(death ~ dow + ns(date, 19 * 6) + ns(tmpd, 6) + ns(rmtmpd, 6) + ns(dptp, 3) + ns(rmdptp, 3) + Lag(pm10tmean, 1), data = as(d0, "data.frame"), family = poisson)
ap <- new("APTSModel", timevar = "date", model = base, exposure = "pm10tmean", summary = ch)
dfmax <- selectTimeDF(ap)

g <- glm(death ~ dow + ns(date, 19 * dfmax) + ns(tmpd, 6) + ns(rmtmpd, 6) + ns(dptp, 3) + ns(rmdptp, 3) + Lag(pm10tmean, 1), data = as(d0, "data.frame"), family = poisson)
ap <- new("APTSModel", timevar = "date", model = g, exposure = "pm10tmean", summary = ch)

sens <- sensitivityAnalysis(ap, 19 * 4:20)
infl <- influenceAnalysis(ap)
